http-port      = 3000
http-port      = ${?BET_SERVICE_HTTP_PORT}

db-url         = ${?BET_SERVICE_DB_URL}

db-user        = ${?BET_SERVICE_DB_USER}

db-password    = ${?BET_SERVICE_DB_PASSWORD}

kafka-brokers  = ${?KAFKA_BROKERS}

bet-placed-topic = "bets.placed"
bet-placed-topic = ${?BET_PLACED_TOPIC}

http-shutdown-timeout = 10 seconds

db-max-pool-size = 10
db-max-pool-size = ${?BET_SERVICE_DB_MAX_POOL_SIZE}

db-min-idle       = 2
db-min-idle       = ${?BET_SERVICE_DB_MIN_IDLE}

db-connection-timeout = 5 seconds