http-port      = 3000
http-port      = ${?BET_SERVICE_HTTP_PORT}

db-url         = "jdbc:postgresql://localhost:5432/betdb"
db-url         = ${?BET_SERVICE_DB_URL}

db-user        = "postgres"
db-user        = ${?BET_SERVICE_DB_USER}

db-password    = "postgres"
db-password    = ${?BET_SERVICE_DB_PASSWORD}

kafka-brokers  = "localhost:19092"
kafka-brokers  = ${?KAFKA_BROKERS}