http-port      = 3001
http-port      = ${?TRADING_SERVICE_HTTP_PORT}

db-url         = "jdbc:postgresql://localhost:5434/tradingdb"
db-url         = ${?TRADING_SERVICE_DB_URL}

db-user        = "postgres"
db-user        = ${?TRADING_SERVICE_DB_USER}

db-password    = "postgres"
db-password    = ${?TRADING_SERVICE_DB_PASSWORD}

http-shutdown-timeout = 10 seconds

db-max-pool-size = 10
db-max-pool-size = ${?TRADING_SERVICE_DB_MAX_POOL_SIZE}

db-min-idle       = 2
db-min-idle       = ${?TRADING_SERVICE_DB_MIN_IDLE}

db-connection-timeout = 5 seconds

kafka-brokers = "localhost:9092"
kafka-brokers = ${?KAFKA_BROKERS}
kafka-group-id = "trading-service-group"
kafka-group-id = ${?KAFKA_GROUP_ID}
kafka-topic = "bet-placed-events"
kafka-topic = ${?KAFKA_TOPIC}